#!/usr/bin/env bash


#VAR=`xrandr | awk '{print $2}'`
##Experimental
#process xranr line by line with awk
#if match, turn off display.
#VAR=xrandr | awk '{print $2}'

XRANDR=`xrandr`
while read $XRANDR
do
    echo-e "$ line \ n"
done 
